name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-07-05
version: '9.5.10'
project: 'drupal'
datestamp: 1688551056
